global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'app_serial'
    static_configs:
      - targets: ['app_serial:8080']

  - job_name: 'app_uuid'
    static_configs:
      - targets: ['app_uuid:8080']

  - job_name: 'app_public_key'
    static_configs:
      - targets: ['app_public_key:8080']